import { createSlice } from "@reduxjs/toolkit"; //used to create Redux slice objects.

export interface BidderState { // specifies the structure of the state managed by the bidder slice.
    bidder: any;
}

export const bidderSlice = createSlice({
    name: "bidder",
    initialState: {
        bidder: null,
    } as BidderState,
    reducers: { //specify how the state should change in response to actions
        login: (state, action) => {
            state.bidder = action.payload;
        },
        logout: (state) => {
            state.bidder = null;
        },
    },
});

export const { login, logout } = bidderSlice.actions; //This exports the action creators (login and logout) generated by the createSlice function, as well as the reducer function
export const selectBidder = (state: { admin: { user: any } }) => //takes the Redux state object as an argument and returns the user property under the admin slice
  state.admin.user;
export default bidderSlice.reducer;
